server:
  port: 8083
spring:
  application:
    name: WISHLIST-SERVICE
  config:
    import: optional:configserver:http://localhost:8088
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
resilience4j:
  circuitbreaker:
      instances:
        wishlist-service:
          register-health-indicator: true
          event-consumer-buffer-size: 10
          failure-rate-threshold: 10
          minimum-number-of-calls: 5
          automatic-transition-from-open-to-half-open-enabled: true
          max-wait-duration-in-half-open-state: 5s
          permitted-number-of-calls-in-half-open-state: 3
          sliding-window-size: 10
          sliding-window-type: COUNT_BASED
          
          
        
    
  