server:
  port: 8081
spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8088 
  datasource:
    url: jdbc:mysql://localhost:3306/movieapp
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
security:
  ignored: /**
 
    
